### ISSUE TITLE
Update to global tools latest nupkg format

### ISSUE THREAD

**Issue by wli3** [aspnet/DotNetTools#383]
Need to update to global tools latest nupkg format. Or the result nupkg cannot be consumed by CLI once https://github.com/dotnet/cli/pull/8414 is merged.  I am referencing [dotnet-watch.nuspec](https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-watch/dotnet-watch.nuspec) 

- [ ]  [DotnetToolSettings.xml](https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-watch/dotnet-watch.nuspec#L24) need to store under TFM/any. [Reference](https://github.com/wli3/cli/blob/9c2a9561850e3cbf3b7db11de1cdc7d44c2745c5/test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalTool/includepublish.nuspec#L17)

- [ ]  Need to add _Microsoft.NETCore.Platforms_ as dependency. The version of the package should be the runtime version/offline package version of Microsoft.NETCore.Platforms. So CLI can find that package from offline cache. [Reference](https://github.com/wli3/cli/blob/9c2a9561850e3cbf3b7db11de1cdc7d44c2745c5/test/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalTool/includepublish.nuspec#L12) (Note version should **not** be 2.0.1. It won’t be in offline cache)

**Comment by natemcmaster** [comment]
>Need to add Microsoft.NETCore.Platforms as dependency.

I don't understand this requirement. Can you clarify? Is this something all global tools packages will have to carry? Is this a workaround?

**Comment by natemcmaster** [comment]
cc @muratg

**Comment by wli3** [comment]
RID is transparent to NuGet, to select correct RID, `Microsoft.NETCore.Platforms` is required to select right RID. In portable case, this package is still needed to ANY given consumer's RID say win-x64. Detail is [here](https://github.com/dotnet/designs-microsoft/blob/dcd81fd56d0b7bcb1bbca3872614bef2778d6f56/proposals/implementation_global_tools.md#handling-self-contained-applications).

Pack tool experience will add this dependency implicitly so producer using pack experience do not need to worry about this.

**Comment by natemcmaster** [comment]
I don't think this is something we want to put into our tool nuspec. It's not actually a dependency of the tool. It seems to me like having Microsoft.NETCore.Platforms in the restore graph is just an implementation detail of how `dotnet install tool` is implemented.

**Comment by natemcmaster** [comment]
@wli3 is Microsoft.NETCore.Platforms  going to be required after you integrate NuGet into dotnet-install-tool? https://github.com/dotnet/cli/pull/8414

**Comment by wli3** [comment]
Yes, and Microsoft.NETCore.Platforms need to be part of the fallbackfolder

**Comment by natemcmaster** [comment]
Fixed in #385

**Comment by wli3** [comment]
Note, that has not been insert to 2.1.3XXX  (preview 1 branch)

**Comment by natemcmaster** [comment]
Can you clarify? Did you mean https://github.com/dotnet/cli/pull/8414 isn’t going into 2.1.300-preview1? Or did you mean the changes to our packages aren’t in 2.1.300-preview1 yet?

**Comment by wli3** [comment]
Sorry, I mean the second. The change of _adding Platforms package to dotnet-watch etc_ has not been inserted to branch 2.1.3XXX yet. Installation of dotnet-watch offline still fails in manual validation.

> Did you mean dotnet/cli#8414 isn’t going into 2.1.300-preview1?

Sorry, that's not what I mean. dotnet/cli#8414 is already in 2.1.300-preview1 builds

**Comment by natemcmaster** [comment]
Ah, I see. I checked [the latest ProdCon build](https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1) output, and they packages in the LZMA are correct now. We will make a PR soon to CLI to update the version of aspnetcore used in local builds of the CLI. We have a few changes we need to make to aspnetcore first, so it may be a few days.

**Comment by natemcmaster** [comment]
FYI - those packages are here at the moment: https://dotnet.myget.org/feed/dotnet-core-test/package/nuget/dotnet-watch/2.1.0-preview1-28181

**Comment by wli3** [comment]
@natemcmaster double check with you, the insertion of dotnet-watch to 2.1.3XXX is done? i see there is no diff between master and 2.1.3xxx on dependency version
